### ISSUE TITLE
interpretation of partial dependence plots in R

### ISSUE THREAD

**Issue by wisamb** [bgreenwell/partial#129]
I've run a logistic regression and XG boosted to predict my data. After running feature analysis, I would like to also look at partial dependence plots to look at possible interactions. Using R and the pdp package, I get the below results. X1 and X2 are predictor variables and Y is the response variable. All 3 variables are categorical. My question is if the x and y axis marks are indicative of the values of the predictor variables? Do the 1-5 for X1 reflect the values of that predictor variable?

The reason I ask, I went to change the order of the values. That is, I made value 2 as value 1, value 3 as value 5, etc. However, the results do not change. The blue cross in the middle keeps its position. If, however, the value are re-coded, it should shift position. I made sure to change the order of the factor levels as well, but still getting the same result. Is this the correct understanding of pdp with categorical variables? 

I also tried to rename the values for X1 and X2 for better readability. It leaves the last value with the number designation (ie, "5"). I take it has to do with the which.class parameter but then why does it leave the last group at all? Is the "focus" class the same thing as a referrant? 

You'll notice in my code below, I included an "NA" in my list of labels so that all labels appear. However, my bigger concern is determining which group belongs to which axis tick mark. Sorry I can't include any data due to it being health data. If the code is not enough, I can create a dummy dataset.

![3gPIn](https://user-images.githubusercontent.com/41888028/203731406-ed60dfec-c53a-45b3-bf66-f3544044b9e6.png)

```
interaction_vars <- c("X1", "X2")

Compute partial dependence data 
pd <- partial(object = xgb_fit,
              pred.var = interaction_vars, 
              train = train_data, 
              type = "classification", 
              prob = TRUE, 
              cats = 3:length(colnames(train_data)))

pdp1 <- plotPartial(pd,
                    scales = list(x = (list(rot = 45, 
                                            labels = c("NA", "group 1",
                                                       "group 2",
                                                       "group 3",
                                                       "group 4",
                                                       "group 5"))),
                                  y = (list(labels = c("NA", "condition 1", 
                                                       "condition 2", 
                                                       "condition 3", 
                                                       "condition 4")))))
```

**Comment by brandongreenwell-8451** [comment]
Hi @wisamb, I saw that you closed this, were you able to resolve your issue(s)?

**Comment by wisamb** [comment]
Hi @brandongreenwell-8451 , the variable needs to be recoded before running the model. The labeling I fixed by adding a blank label for the first value. I verified that it's correctly labeled by running partial dependence in randomForest.

**Comment by wisamb** [comment]
@brandongreenwell-8451, could you tell me why there are differences in yhat values between randomForest and pdp packages? They tell the same story but the difference is less pronounced with pdp. According to the literature and R package documentation, both use the same function to calculate yhat. So why the difference?
![pdp_pdp](https://user-images.githubusercontent.com/41888028/204115004-ecd6878f-44bd-44b9-9f23-81f4645ab9b0.JPG)
![pdp_rf](https://user-images.githubusercontent.com/41888028/204115006-bc16016e-16a3-4253-a2e9-5f0bb202ac9f.JPG)

**Comment by bgreenwell** [comment]
Hi @wisamb, do you have the code used to produce each plot? From inspection, it looks like the top figure is on the probability scale (binary outcome?) while the bottom figure is on the traditional centered logit scale.

**Comment by bgreenwell** [comment]
The randomForest package will only produce plots on the centered logit scale, while pdp will do either.

**Comment by wisamb** [comment]
@bgreenwell, that was it. Many thanks!
