### ISSUE TITLE
plots differ based on algorithm

### ISSUE THREAD

**Issue by wisamb** [bgreenwell/partial#131]
Can you tell me why I get the first plot from `pdp::partial` from a random forest algorithm (either randomForest or ranger package)? Rather than the second plot, which I get running the same code, same data but using an xgboost? How can I get the second plot using the either randomForest or ranger package?

![Capture](https://user-images.githubusercontent.com/41888028/229005187-bbc3c1f9-3851-4dc6-a7dc-c53edec072cd.JPG)
![2](https://user-images.githubusercontent.com/41888028/229005233-d1ba757d-a88a-45fb-9c86-885c2617682a.JPG)

**Comment by bgreenwell** [comment]
Hi @wisamb i suspect it’s because the variable I question is treated as factor in the random forest but numeric (as all inputs) in xgboost, and the plotting behavior depends on the feature types.

**Comment by wisamb** [comment]
Thank you @bgreenwell! That was exactly it.
